# Repository-specific PR-Agent configuration for skatamatic/AI_PRTest
# This file overrides global settings

[config]
model = "anthropic/claude-3-5-haiku-20241022"
model_reasoning = "o4-mini"
reasoning_effort = "low"